---
- name: Run Terraform and Python scripts, then execute Ansible playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run terraform output -json
      shell: terraform output -json > terraform_output.json
      args:
        chdir: /home/ubuntu/Desktop/docker-swarm-infra

    - name: Run Python script to generate inventory
      command: python3 generate_inventory.py
      args:
        chdir: /home/ubuntu/Desktop/docker-swarm-infra

    - name: Remove terraform_output.json
      shell: rm terraform_output.json
      args:
        chdir: /home/ubuntu/Desktop/docker-swarm-infra    

- name: Install Docker and Docker Swarm on Manager Node
  hosts: manager
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - ansible
        state: present

    - name: Add an apt signing key for docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  
    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
  
    - name: Update cache & Install docker
      ansible.builtin.apt:
        update_cache: yes
        state: present
        pkg:
        - docker-ce
  
    - name: Ensure Docker service is enabled and started
      ansible.builtin.systemd_service:
        state: started
        name: docker    
        enabled: yes

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      register: swarm_init

    - name: Save the join token for workers
      shell: docker swarm join-token worker -q
      register: worker_token
      run_once: true

    - name: Save join command to a file
      copy:
        dest: /tmp/worker_join_command.sh
        content: "docker swarm join --token {{ worker_token.stdout }} {{ ansible_host }}:2377\n"

    - name: Copy worker playbook to manager node
      copy:
        src: worker.yml
        dest: /home/ubuntu/worker.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy inventory to manager node
      copy:
        src: inventory.ini
        dest: /home/ubuntu/inventory.ini
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy key file to manager node
      copy:
        src: id_rsa.pem
        dest: /home/ubuntu/id_rsa.pem
        owner: ubuntu
        group: ubuntu
        mode: '0400'

    - name: Run worker playbook from manager node
      command: ansible-playbook /home/ubuntu/worker.yml -i /home/ubuntu/inventory.ini -e 'ansible_ssh_private_key_file=./id_rsa.pem' -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
      register: ansible_worker_output

    - name: Print worker playbook output
      debug:
        var: ansible_worker_output.stdout_lines
