---
- name: Setup Docker Swarm
  hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: true
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tasks:
    - name: Update cache & Install apt packages
      ansible.builtin.apt:
        update_cache: yes
        state: present
        pkg:
          - nfs-common
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
  
    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  
    - name: Add Docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
  
    - name: Update cache & Install Docker
      ansible.builtin.apt:
        update_cache: yes
        state: present
        pkg: "{{ docker_packages }}"
  
    - name: Ensure Docker service is enabled and started
      ansible.builtin.systemd:
        state: started
        name: docker    
        enabled: yes

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Setup Docker Swarm
  hosts: manager
  remote_user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: Leave Docker Swarm (if currently joined)
      shell: docker swarm leave --force
      ignore_errors: true

    - name: Initialize the Swarm on the manager node
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      register: swarm_init
      ignore_errors: true

    - name: Get the join token for worker nodes
      shell: docker swarm join-token worker -q
      when: swarm_init.rc == 0
      register: worker_join_token

    - name: Set fact with join token
      ansible.builtin.set_fact:
        join_token: "docker swarm join --token {{ worker_join_token.stdout }} {{ ansible_host }}:2377"
      when: worker_join_token.stdout is defined

    - name: Print token
      debug:
        msg: docker swarm join --token {{ worker_join_token.stdout }} {{ ansible_host }}:2377
      when: worker_join_token is defined      

- name: Join Docker Swarm as worker nodes
  hosts: worker
  remote_user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: Leave Docker Swarm (if currently joined)
      shell: docker swarm leave
      ignore_errors: true

    - name: Join Docker Swarm as worker
      ansible.builtin.shell:
        cmd: "{{ hostvars[groups['manager'][0]]['join_token'] }}"